# Generated by Django 4.2 on 2024-03-13 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('c', models.FloatField(help_text='A float value between 0 and 20', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('t', models.FloatField(help_text='A float value between 0 and 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('graph_file', models.FileField(help_text='Upload a graph txt file', upload_to='graphs/')),
                ('image_file', models.ImageField(help_text='Upload an image file', upload_to='images/')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
